service: layers-nodejs-module

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: "hello"
          method: get
    layers:
      - { Ref: NodeModulesLambdaLayer } # identifica o arn automaticamente na hora da build

layers:
  NodeModules:
    path: layer
    compatibleRuntimes:
      - nodejs12.x
