service: tooling-s3-sqs

frameworkVersion: "2"

configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-localstack
  - serverless-mocha-plugin
  - serverless-offline # sempre deixar por ultimo

custom:
  localstack:
    stages: # list of stages for which the plugin should be enabled
      - local
    edgePort: 4566 # optional - LocalStack edge port to connect to
    lambda:
      mountCode: true # Enable this flag to improve performance
    debug: true
    autostart: true
  serverless-offline:
    useChildProcesses: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
